services:
  web:
    build: .
    container_name: django_app
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    depends_on:
      - db
      - rabbitmq
      - redis

  db:
    image: postgres:15
    container_name: postgres_db
    environment:
      POSTGRES_DB: ecommerce
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"

  redis:
    image: redis:7
    container_name: redis
    ports:
      - "6379:6379"

  celery:
    build: .
    container_name: celery_worker
    command: celery -A src worker -l info
    volumes:
      - .:/app
    depends_on:
      - rabbitmq
      - redis
      - db

volumes:
  postgres_data: